modLoader = "javafml" #mandatory
loaderVersion = "[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "All Rights Reserved"

[[mods]] #mandatory
modId = "zencraft" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "ZenCraft" #mandatory
authors = "ArrowsendGaming" #optional
description = '''

'''
[[dependencies.zencraft]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[43,)" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.zencraft]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"